#!/usr/bin/env bash
set -euo pipefail

VENDOR_ROOT="${AGENT_HARNESS_VENDOR_DIR:-$HOME/.local/share/agent-harness/vendor}"
REPO_DIR="$VENDOR_ROOT/TencentDB-Agent-Memory"
DEPLOY_DIR="$REPO_DIR/deploy/global-images"
CONFIG_DIR="$HOME/.config/agent-harness"
CONFIG_FILE="$CONFIG_DIR/memory.env"
UPSTREAM="https://github.com/TencentCloud/TencentDB-Agent-Memory.git"
NONINTERACTIVE="${AGENT_HARNESS_NONINTERACTIVE:-0}"

warn() { printf 'WARN    %s\n' "$*" >&2; }
ok() { printf 'OK      %s\n' "$*"; }

command -v git >/dev/null 2>&1 || { echo "git is required" >&2; exit 127; }
command -v docker >/dev/null 2>&1 || { echo "Docker is required" >&2; exit 127; }
command -v curl >/dev/null 2>&1 || { echo "curl is required" >&2; exit 127; }

mkdir -p "$VENDOR_ROOT" "$CONFIG_DIR"

if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "Cloning TencentDB Agent Memory into $REPO_DIR"
  git clone --depth 1 "$UPSTREAM" "$REPO_DIR"
else
  ok "TencentDB Agent Memory checkout already exists at $REPO_DIR"
fi

if [[ ! -f "$DEPLOY_DIR/.env" ]]; then
  cp "$DEPLOY_DIR/.env.example" "$DEPLOY_DIR/.env"
  echo "Created $DEPLOY_DIR/.env from upstream template."
fi

get_env() {
  local key="$1"
  sed -n "s/^${key}=\([^#]*\).*/\1/p" "$DEPLOY_DIR/.env" | tail -n 1 | sed -E 's/[[:space:]]+$//'
}

set_env() {
  local key="$1"
  local value="$2"
  python3 - "$DEPLOY_DIR/.env" "$key" "$value" <<'PY'
from pathlib import Path
import sys
path = Path(sys.argv[1])
key = sys.argv[2]
value = sys.argv[3]
lines = path.read_text().splitlines()
for i, line in enumerate(lines):
    if line.startswith(key + "="):
        lines[i] = f"{key}={value}"
        break
else:
    lines.append(f"{key}={value}")
path.write_text("\n".join(lines) + "\n")
PY
}

needs_memory_llm=0
for key in MEMORY_LLM_BASE_URL MEMORY_LLM_API_KEY MEMORY_LLM_MODEL; do
  value="$(get_env "$key")"
  if [[ -z "$value" || "$value" == "REPLACE_ME" ]]; then
    needs_memory_llm=1
  fi
done

if [[ "$needs_memory_llm" -eq 1 ]]; then
  if [[ "$NONINTERACTIVE" == "1" || ! -t 0 ]]; then
    warn "Memory sidecar cloned, but MEMORY_LLM_* is not configured."
    cat <<NEXT
Configure these values in:
  $DEPLOY_DIR/.env

Required:
  MEMORY_LLM_BASE_URL=<OpenAI/Anthropic-compatible endpoint>
  MEMORY_LLM_API_KEY=<key>
  MEMORY_LLM_MODEL=<model>
  MEMORY_LLM_PROTOCOL=openai   # or anthropic

Then rerun:
  agent-harness ready . --skip-ponytail --skip-chatgpt-web
NEXT
    exit 0
  fi

  echo "Tencent Memory uses an LLM for extraction/knowledge. Configure only that memory LLM now."
  current_base="$(get_env MEMORY_LLM_BASE_URL)"
  current_model="$(get_env MEMORY_LLM_MODEL)"
  current_protocol="$(get_env MEMORY_LLM_PROTOCOL)"
  [[ "$current_base" == "REPLACE_ME" ]] && current_base=""
  [[ "$current_model" == "REPLACE_ME" ]] && current_model=""
  [[ -z "$current_protocol" ]] && current_protocol="openai"

  read -r -p "Memory LLM base URL${current_base:+ [$current_base]}: " input_base
  input_base="${input_base:-$current_base}"
  read -r -p "Memory LLM model${current_model:+ [$current_model]}: " input_model
  input_model="${input_model:-$current_model}"
  read -r -p "Memory LLM protocol [$current_protocol]: " input_protocol
  input_protocol="${input_protocol:-$current_protocol}"
  read -r -s -p "Memory LLM API key: " input_key
  echo

  [[ -n "$input_base" && -n "$input_model" && -n "$input_key" ]] || {
    echo "Memory LLM base URL, model, and API key are required." >&2
    exit 2
  }

  command -v python3 >/dev/null 2>&1 || { echo "python3 is required to update Tencent's .env safely" >&2; exit 127; }
  set_env MEMORY_LLM_BASE_URL "$input_base"
  set_env MEMORY_LLM_API_KEY "$input_key"
  set_env MEMORY_LLM_MODEL "$input_model"
  set_env MEMORY_LLM_PROTOCOL "$input_protocol"
fi

GATEWAY_KEY="$(get_env MEMORY_CORE_GATEWAY_API_KEY)"
cat > "$CONFIG_FILE" <<CFG
# Generated by agent-harness. Safe defaults for local sidecar access.
AGENT_MEMORY_URL=http://127.0.0.1:8420
AGENT_MEMORY_SERVICE_ID=default
AGENT_MEMORY_GATEWAY_API_KEY=$GATEWAY_KEY
CFG
chmod 600 "$CONFIG_FILE"
ok "Memory CLI config written to $CONFIG_FILE"

if docker info >/dev/null 2>&1; then
  ok "Docker daemon reachable"
else
  warn "Docker is installed but the daemon is not reachable. Start Docker and rerun this setup."
  exit 1
fi

if curl -fsS --max-time 2 http://127.0.0.1:8420/health >/dev/null 2>&1; then
  ok "TencentDB Agent Memory core already reachable on :8420"
else
  echo "Starting Tencent memory-core only (no Tencent model proxy)..."
  (cd "$DEPLOY_DIR" && ./start-memory-core.sh)
fi

if curl -fsS --max-time 2 http://127.0.0.1:8125 >/dev/null 2>&1; then
  ok "TencentDB Memory Hub already reachable on :8125"
else
  echo "Starting Tencent memory-hub / knowledge service..."
  (cd "$DEPLOY_DIR" && ./start-memory-hub.sh)
fi

cat <<'NEXT'
Tencent memory sidecar is ready.

This harness intentionally does NOT start Tencent's memory-proxy (:8096).
`codex-chatgpt-web` remains the Codex/ChatGPT model + tool bridge.
Tencent runs only as memory-core + memory-hub/knowledge.

Panel: http://127.0.0.1:8125
Core:  http://127.0.0.1:8420
Knowledge: http://127.0.0.1:8424

For stronger team/agent isolation and asset management, use the Memory Hub panel
to create Team/User/Agent records once. The `agent-memory` CLI itself uses a
repository-prefixed retrieval namespace and the default local data bucket.
NEXT
