#!/usr/bin/env bash
set -euo pipefail

VENDOR_ROOT="${AGENT_HARNESS_VENDOR_DIR:-$HOME/.local/share/agent-harness/vendor}"
REPO_DIR="$VENDOR_ROOT/TencentDB-Agent-Memory"
DEPLOY_DIR="$REPO_DIR/deploy/global-images"
CONFIG_DIR="$HOME/.config/agent-harness"
CONFIG_FILE="$CONFIG_DIR/memory.env"
UPSTREAM="https://github.com/TencentCloud/TencentDB-Agent-Memory.git"
NONINTERACTIVE="${AGENT_HARNESS_NONINTERACTIVE:-0}"

warn() { printf 'WARN    %s\n' "$*" >&2; }
ok() { printf 'OK      %s\n' "$*"; }

command -v git >/dev/null 2>&1 || { echo "git is required" >&2; exit 127; }
command -v docker >/dev/null 2>&1 || { echo "Docker is required" >&2; exit 127; }

mkdir -p "$VENDOR_ROOT" "$CONFIG_DIR"

if [[ ! -d "$REPO_DIR/.git" ]]; then
  echo "Cloning TencentDB Agent Memory into $REPO_DIR"
  git clone --depth 1 "$UPSTREAM" "$REPO_DIR"
else
  ok "TencentDB Agent Memory checkout already exists at $REPO_DIR"
fi

if [[ ! -f "$DEPLOY_DIR/.env" ]]; then
  cp "$DEPLOY_DIR/.env.example" "$DEPLOY_DIR/.env"
  echo "Created $DEPLOY_DIR/.env from upstream template."
fi

GATEWAY_KEY="$(sed -n 's/^MEMORY_CORE_GATEWAY_API_KEY=//p' "$DEPLOY_DIR/.env" | tail -n 1 | tr -d '\r')"
cat > "$CONFIG_FILE" <<CFG
# Generated by agent-harness. Safe defaults for local sidecar access.
AGENT_MEMORY_URL=http://127.0.0.1:8420
AGENT_MEMORY_SERVICE_ID=default
AGENT_MEMORY_GATEWAY_API_KEY=$GATEWAY_KEY
CFG
chmod 600 "$CONFIG_FILE"
ok "Memory CLI config written to $CONFIG_FILE"

if docker info >/dev/null 2>&1; then
  ok "Docker daemon reachable"
else
  warn "Docker is installed but the daemon is not reachable. Start Docker and rerun this setup."
  exit 1
fi

if curl -fsS --max-time 2 http://127.0.0.1:8420/health >/dev/null 2>&1; then
  ok "TencentDB Agent Memory is already running on :8420"
  exit 0
fi

if [[ "$NONINTERACTIVE" == "1" || ! -t 0 ]]; then
  warn "Memory is installed but not started because Tencent's first boot is interactive (LLM credentials)."
  cat <<NEXT
Run once in an interactive terminal:
  cd "$DEPLOY_DIR"
  ./start-all.sh

The upstream script will prompt for the Memory LLM and proxy LLM configuration,
validate them, and start memory-core, memory-hub, and proxy containers.
The agent-harness architecture uses memory-core/hub as a sidecar and does NOT point
Codex at Tencent's :8096 model proxy when codex-chatgpt-web is active.
NEXT
  exit 0
fi

cat <<'NOTICE'
TencentDB Agent Memory first boot is interactive because its memory extraction and
knowledge services need an LLM endpoint. The upstream start-all.sh will ask for:
- MEMORY_LLM_* (used by memory/knowledge extraction)
- PROXY_UPSTREAM_* (required by the upstream three-service launcher)

The harness will NOT configure Codex to use Tencent's proxy. codex-chatgpt-web remains
the Codex model bridge; Tencent is used as a local memory sidecar.
NOTICE

read -r -p "Run Tencent's interactive Docker setup now? [Y/n] " answer
if [[ -z "$answer" || "$answer" =~ ^[Yy]$ ]]; then
  (cd "$DEPLOY_DIR" && ./start-all.sh)
else
  warn "Memory containers not started. Run $DEPLOY_DIR/start-all.sh later."
fi
